# fly.toml app configuration file generated for 61-050-message-board on 2023-11-20T09:55:33-03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "61-050-message-board"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
